"""added PerformanceHistory

Revision ID: 00be9346fec4
Revises: 04987c9fc86b
Create Date: 2023-12-17 14:23:34.390495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00be9346fec4'
down_revision = '04987c9fc86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('performance', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['profile'], ['profile.id'], name=op.f('fk_performance_history_profile_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_history'))
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('performance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performance', sa.VARCHAR(length=2000), nullable=False))

    op.drop_table('performance_history')
    # ### end Alembic commands ###
