"""empty message

Revision ID: 465ff44ce89b
Revises: 
Create Date: 2023-12-02 22:13:29.827273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465ff44ce89b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('performance', sa.String(length=2000), nullable=False),
    sa.Column('preferred_categories', sa.String(length=2000), nullable=False),
    sa.Column('date_created', sa.String(), nullable=True),
    sa.Column('last_active', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problem_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['profile_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_profile', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('performance')
        batch_op.drop_column('preferred_categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_categories', sa.VARCHAR(length=2000), server_default=sa.text("'[]'"), nullable=False))
        batch_op.add_column(sa.Column('performance', sa.VARCHAR(length=2000), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('current_profile')

    with op.batch_alter_table('problem_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('profile_id')

    op.drop_table('profile')
    # ### end Alembic commands ###
