"""Initial migration.

Revision ID: 59d38fc46d9e
Revises: 97f7561b5088
Create Date: 2024-09-08 21:19:35.065439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d38fc46d9e'
down_revision = '97f7561b5088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uw_score', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem_history', schema=None) as batch_op:
        batch_op.drop_column('uw_score')

    # ### end Alembic commands ###
